# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'NikosWetterApp' do
pod 'AMSlideMenu', '~> 1.5'
pod 'SwiftHEXColors', '~> 1.0'
end

target 'NikosWetterAppTests' do

end

